### ISSUE TITLE
Flicker on page change/refresh on Firefox

### ISSUE THREAD

**Issue by jcrist** [dask/dask-sphinx-theme#17] opened 2019-09-18 18:06 UTC
This may be an issue with the readthedocs theme instead of dask's. On firefox, I see a very noticeable flicker on page load for any dask docs page (for example https://docs.dask.org/en/latest/). It looks like this is the CSS formatting (briefly see what looks like a less formatted page). I use firefox as my primary browser, in most cases page load fast and cleanly, so I assume there's something weird with this page leading to this behavior. I am not a web dev, no idea how to investigate this further.

![out](https://user-images.githubusercontent.com/2783717/65173686-f2d8b400-da14-11e9-8e4e-cd34af1b9e49.gif)

**Comment by mrocklin** [comment] 2019-09-18 19:32
@jrbourbeau @jacobtomlinson any thoughts?

**Comment by jcrist** [comment] 2019-09-18 21:25
Someone internal pointed me to this: https://webhint.io/scanner/026e513b-8f02-44e6-a441-24a9f6f6cb85

Not sure how to interpret all the results, but there's a few things on there that look worth fixing.

**Comment by jacobtomlinson** [comment] 2019-09-19 08:13
Google lighthouse is also useful for this 

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdocs.dask.org%2Fen%2Flatest&tab=desktop

Looking at the page source it seems there is a lot of JavaScript that gets loaded before the CSS. So this is likely to be a JavaScript performance issue. Ordinarily these script tags should go at the end of the body unless there is an exceptional reason why then are needed before the rest of the DOM.

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/1610850/65225803-aa290580-dabd-11e9-9753-7fcb38bd93bb.png">

**Comment by jacobtomlinson** [comment] 2019-10-16 09:29
It looks like this needs to be changed upstream in rtd.

@jcrist can you test the upstream theme and see if you can reproduce the same issue? https://sphinx-rtd-theme.readthedocs.io/en/stable/

**Comment by jacobtomlinson** [comment] 2019-10-24 11:52
Ref readthedocs/sphinx_rtd_theme#847

**Comment by jsignell** [comment] 2021-10-05 13:31
I think we can probably close this issue, now that we depend on the executable books theme.

**Closed** 2021-10-05 13:34 UTC
